CREATE TABLE IF NOT EXISTS products (
  id TEXT NOT NULL PRIMARY KEY DEFAULT(uuid()),
  name TEXT NOT NULL UNIQUE,
  price REAL NOT NULL CHECK(price >= 0),
  category TEXT NOT NULL,
  is_deleted BOOLEAN NOT NULL DEFAULT false
);

